### ISSUE TITLE
Popover first opens "upside down" with mdePopoverTriggerOn="hover"

### ISSUE THREAD

**Issue by malinges** [material-extended/mde#28] opened 2018-06-04 15:43 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behaviour?
Correct orientation:
![capture d ecran 2018-06-04 a 11 37 09](https://user-images.githubusercontent.com/1636924/40926947-74d5ce0e-67eb-11e8-85f8-139870d8dbd8.png)

#### What is the current behaviour?
Incorrect orientation when hovering over the trigger _for the first time_ (subsequent hovers work fine):
![capture d ecran 2018-06-04 a 11 34 32](https://user-images.githubusercontent.com/1636924/40926877-4e4b655a-67eb-11e8-98e6-d2b5012b488d.png)

#### What are the steps to reproduce?
Simply use `mdePopoverTriggerOn="hover"` in the stackblitz template:
https://stackblitz.com/edit/mde-popover-7cy3ta

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?
```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.5
Node: 8.11.2
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.5
@angular-devkit/build-angular      0.6.5
@angular-devkit/build-optimizer    0.6.5
@angular-devkit/core               0.6.5
@angular-devkit/schematics         0.6.5
@angular/cdk                       6.2.0
@angular/cli                       6.0.5
@angular/material                  6.2.0
@angular/material-moment-adapter   6.2.0
@ngtools/webpack                   6.0.5
@schematics/angular                0.6.5
@schematics/update                 0.6.5
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
    
```

**Comment by joejordanbrown** [comment] 2018-06-08 00:15
@malinges 

Thanks for reporting this.

I will investigate this issue, something must have changed when updating to the latest CDK.

I would like to refactor the way the arrow position is set and styled at some point, but I'm struggling to find the time at the moment.

**Comment by cerbaro** [comment] 2018-07-13 21:52
@joejordanbrown 

Thanks for sharing and maintaining this package. It helped me a lot.
I'll take a look on the codes and try to contribute.. let's see.

@malinges 
I was able to get it working adding  `mdePopoverPositionY="above"` to the popover element. 
Just in case you wanna try..

Best,

**Comment by ester969** [comment] 2018-07-15 17:57
i got error when click mdepopover in angular 5 : this._overlay.position(...).flexibleConnectedTo is not a function
please help !!
 <button mat-raised-button color="primary"
    [mdePopoverTriggerFor]="appPopover"
    mdePopoverTriggerOn="click">
    Show Popover
  </button>

  <mde-popover #appPopover="mdePopover" [mdePopoverOverlapTrigger]="false">
    <mat-card style="max-width: 300px">
      <mat-card-content>
      A material design popover component created using Angular version 4 with the Angular CDK.
      </mat-card-content>
    </mat-card>
  </mde-popover>

**Comment by Nikhil-Pahwa** [comment] 2018-09-27 20:09
Any update on this? When this issue will be fixed?
I tried `mdePopoverPositionY="above"` to the popover element but it does not work. Still popover opens upside down on first.

**Comment by tesfayet11** [comment] 2018-11-29 16:19
Any Update on this issue?` mdePopoverPositionY="above"` doesn't solve it.

**Comment by rdgfuentes** [comment] 2018-11-30 14:33
I've been looking into this issue and at first glance it seems to be caused by the persistence of the previous popover's arrow direction that was shown.  I also noted that when this bug appears, the arrow changes to its correct orientation right after you move the mouse over the element that triggers the popover. I'll keep investigating and I'll try to fix it 🤞

**Comment by kevinLourencoDev** [comment] 2019-05-11 10:26
Hello all, I wanted to implement this popover and i was blocked because of this beug. It's not user friendly in case there is action into the content like an external link cause the popover change his direction on mouseleave and disappear... The user have to rehover the element in order to click on the link into the popover content. 

<img width="415" alt="Capture d’écran 2019-05-11 à 12 11 11" src="https://user-images.githubusercontent.com/45124458/57568323-fb293e80-73e5-11e9-9508-53313ed1c02c.png">

For those who need that work well and can't wait for contributors implementation ( who seem to not to longer be reactive ) there is a simple quick fix on CSS, force the position of popover : 

`  
.mde-popover-content {
    padding-top: 8px !important;
    margin-top: 0 !important;
  }
`
Then to avoid visual problems with arrow not showing directly i suggest to remove it : 

`  
.mde-popover-direction-arrow {
    display: none;
  }
`

It work perfectly and in my UX point of view i don't think that the arrow is indispensable. 

Nevertheless i waiting for a real fix, i don't know what it has happened and why validation not occured  but it's seem to be he good way : [Pull 45](https://github.com/material-extended/mde/pull/45)

**Comment by joejordanbrown** [comment] 2019-05-14 22:53
@malinges @cerbaro @Nikhil-Pahwa @tesfayet11 @rdgfuentes @kevinLourencoDev 

Good news, this has now been fixed. I have merged and published a new package.

Please thank @kostia-lev for creating a pull request with the relevant fix.

**Closed** 2019-05-14 22:57 UTC
Labels: P2: required, bug, completed, help wanted
